---
version: "2"

volumes:
  postgresql_data:
    driver: local

services:
  postgresqldb:
    image: "bitnami/postgresql:14.2.0"
    environment:
      POSTGRESQL_USER: ${POSTGRESQL_USER}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
    ports:
      - "${POSTGRESQL_PORT}:5432"
    volumes:
      - "postgresql_data:/bitnami/postgresql"
